catalog:
  default:
    type: dynamodb
    s3.region: us-east-1

  glue:
    type: glue
    glue.region: us-east-1

follower-catalogs:
  - glue

server:
  defaults:
    warehouse: s3://warehouse/

host: 0.0.0.0
port: 8080

log:
  debug: true
