catalog:
  rest:
    type: rest
    uri: "http://localhost:8181"

  sql:
    type: sql
    uri: sqlite:////tmp/iceberg.db
    sql.driver: sqlite3
    sql.dialect: sqlite
    init_catalog_tables: true

  glue:
    type: glue
    glue.region: us-east-1
