catalog:
  default:
    type: sql
    sql.driver: sqlite3
    sql.dialect: sqlite
    init_catalog_tables: true
    s3.region: us-east-1
    s3.endpoint: http://localhost:9000
    s3.access-key-id: admin
    s3.secret-access-key: password

server:
  defaults:
    warehouse: s3://warehouse/

host: 0.0.0.0
port: 8080

log:
  debug: true
